scrape_configs:
  - job_name: 'opscenter'
    scrape_interval: 60s
    scrape_timeout: 60s
    scheme: https
    metrics_path: /onyx/metrics
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['192.168.10.45:9443']
